(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var nqa=function(a){a.u||(a.u=new g.Un,g.H(a,a.u));return a.u},J2=function(a){a.R("cardstatechange",g.vL(a)&&g.wL(a)?1:0)},oqa=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Wj&&a.dataset){if(g.ic()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.gd("pollChoiceIndex"))},pqa=function(a){return Math.pow(a,3)},qqa=function(a){return 3*a*a-2*a*a*a},K2=function(a,b){(0,g.y)(b,function(c){c={csn:a,
ve:g.Er(c),eventType:4};var d={fk:g.Pr(a),ni:a};"UNDEFINED_CSN"==a?g.bs("visualElementShown",c,d):g.Vq("visualElementShown",c,g.cr,d)})},L2=function(a,b){(0,g.y)(b,function(c){var d=void 0;
d=void 0===d?!1:d;c={csn:a,ve:g.Er(c),eventType:d?16:8};d={fk:g.Pr(a),ni:a,pE:d};"UNDEFINED_CSN"==a?g.bs("visualElementHidden",c,d):g.Vq("visualElementHidden",c,g.cr,d)})},O2=function(a){a=g.Na(a);
delete M2[a];g.Yb(M2)&&N2&&N2.stop()},sqa=function(){N2||(N2=new g.J(function(){rqa()},20));
var a=N2;a.isActive()||a.start()},rqa=function(){var a=(0,g.I)();
g.Lb(M2,function(b){tqa(b,a)});
g.Yb(M2)||sqa()},P2=function(a,b,c,d){g.Jn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.w=a;this.J=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.H=0;this.F=null},tqa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.H=1E3/(b-a.F);a.F=b;uqa(a,a.progress);1==a.progress?(a.o=0,O2(a),a.wd(),a.A()):1==a.o&&a.ht()},uqa=function(a,b){g.Ka(a.G)&&(b=a.G(b));
a.coords=Array(a.w.length);for(var c=0;c<a.w.length;c++)a.coords[c]=(a.J[c]-a.w[c])*b+a.w[c]},vqa=function(a,b){g.le.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.H;this.state=b.o},Q2=function(a,b,c,d,e){P2.call(this,b,c,d,e);
this.element=a},R2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
Q2.call(this,a,b,c,d,e)},S2=function(a){g.B.call(this);
this.u=a||window;this.o=[]},wqa=function(a,b,c,d){c=(0,g.x)(c,d||a.u);
b=g.Kq(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},T2=function(a){return a.baseUrl||null},xqa=function(a,b,c){function d(sb){var Ya=sb.hovercardButton;
if(!Ya)return null;Ya=Ya.subscribeButtonRenderer;if(!Ya)return null;var uc=f(Ya.unsubscribedButtonText),ef=f(Ya.subscribedButtonText);if(Ya.subscribed){var ff=f(Ya.subscriberCountWithUnsubscribeText);var zh=f(Ya.subscriberCountText)}else ff=f(Ya.subscriberCountText),zh=f(Ya.subscriberCountWithSubscribeText);var gf=null;return sb.signinEndpoint&&(gf=g.Tb(sb,"signinEndpoint","webNavigationEndpointData","url"),!gf)?null:uc&&(ef||gf)?{subscribed:Ya.subscribed,subscribeText:uc,subscribeCount:ff,unsubscribeText:ef,
unsubscribeCount:zh,enabled:Ya.enabled,signinUrl:gf,classic:sb.useClassicSubscribeButton}:null}
function e(sb){if(sb){var Ya=[],uc=sb.videoId;uc&&Ya.push("v="+uc);(uc=sb.playlistId)&&Ya.push("list="+uc);(sb=sb.startTimeSeconds)&&Ya.push("t="+sb);return"/watch?"+Ya.join("&")}}
function f(sb){if(!sb)return null;var Ya=sb.simpleText;return Ya?Ya:sb.runs?(0,g.A)(sb.runs,function(uc){return uc.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,q=null,t=null,u=null,z=null,C=!1,D=null,E=null,G=null,F=null,ka=null;if("VIDEO"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,t=f(b.videoDuration);else if("PLAYLIST"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,u=f(b.playlistLength);else if("CHANNEL"==k){if(C=g.Tb(l,"browseEndpoint","browseId"))z=C,m="/channel/"+z;n=!1;q="new";(C=!!b.isSubscribe)?D=d(b):E=f(b.subscribersText)}else"WEBSITE"==
k?((G=g.Tb(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==k&&(b.productPrice&&(F=f(b.productPrice)),b.additionalFeesText&&(ka=f(b.additionalFeesText)),(n=g.Tb(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=g.Tb(b,"title","accessibility","accessibilityData","label");var X=b.endpoint?b.endpoint.clickTrackingParams:null,Ab="";if(b.metadata){var Hc=f(b.metadata);Hc&&(Ab=Hc)}return{id:"element-"+c,type:k,title:f(b.title),metadata:Ab,callToAction:f(b.callToAction),
rw:b.image,iconUrl:G,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:t,playlistLength:u,channelId:z,subscribeButton:D,subscribersText:E,isSubscribe:C,targetUrl:m,QF:n,Nb:{itct:X},KO:q,Wj:a?a:null,UF:b.isPlaceholder,impressionUrls:(0,g.A)(b.impressionUrls||[],T2),GF:(0,g.A)(b.hovercardShowUrls||[],T2),clickUrls:(0,g.A)(l.loggingUrls||[],T2),visualElement:g.Dr(b.trackingParams),
productPrice:F,additionalFeesText:ka}},U2=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=(0,g.A)(a.impressionUrls||[],T2);a.trackingParams&&(c.visualElement=g.Dr(a.trackingParams));var d=(0,g.A)(a.elements||[],function(e,f){return xqa(b,e,f)});
c.elements=(0,g.Yd)(d,function(e){return!!e});
return c},V2=function(a){g.HP.call(this,a);
this.A=this.u=null;this.o={};this.F={};this.C=this.w=null;this.H=[];a=a.N();this.J=g.wx(a)||g.yx(a);this.P=!0;this.G=0;this.B=new g.P(this);g.H(this,this.B);this.B.L(this.player,g.RD("creatorendscreen"),this.zG);this.B.L(this.player,"crx_creatorendscreen",this.AG);this.B.L(this.player,"resize",this.Fy);this.B.L(window,"focus",this.GN);this.load();var b=g.Sd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.ie(this,function(){g.Xd(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},yqa=function(a){return a.player.getVideoData().uc?"current":a.J?"new":"current"},W2=function(a){return"creator-endscreen-editor"===a.player.N().playerStyle},X2=function(a,b,c){c=void 0===c?!0:c;
g.YQ(a.player.app,"creatorendscreen",void 0);a.w&&(a.w.dispose(),a.w=null,a.C.dispose(),a.C=null);for(var d in a.o)a.o[d].dispose();a.o={};a.F={};0<a.H.length&&(a.H.forEach(function(l){l.dispose()}),a.H.length=0);
a.G=0;if((a.u=b)&&b.elements){c&&zqa(a);c=[];d=new g.OD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.N().o||(a.w=new g.V({D:"div",I:"ytp-ce-shadow"}),g.GL(a.player,a.w.element,4),a.C=new g.$L(a.w,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=Aqa(a,e);a.o[e.id]=f;a.F[e.id]=e;g.GL(a.player,f.element,4);var k=new g.OD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);Bqa(a,f,e)}g.CL(a.player,c);
a.Fy()}},zqa=function(a){var b=g.Mr(),c=g.Or();
c&&b&&a.u.visualElement&&g.cs(c,b,[a.u.visualElement])},Aqa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={D:"div",X:["ytp-ce-element","ytp-ce-video"],M:{tabindex:"0","aria-label":b.Wj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-covering-image",M:Y2(b)},{D:"div",I:"ytp-ce-covering-shadow-top"},{D:"a",I:"ytp-ce-covering-overlay",M:{href:Z2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",X:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],M:{dir:g.dn(b.title||"")},W:b.title},{D:"div",I:"ytp-ce-video-duration",W:b.videoDuration}]}]};
c=new g.V(c);break;case "PLAYLIST":c={D:"div",X:["ytp-ce-element","ytp-ce-playlist"],M:{tabindex:"0","aria-label":b.Wj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-covering-image",M:Y2(b)},{D:"div",I:"ytp-ce-covering-shadow-top"},{D:"a",I:"ytp-ce-covering-overlay",M:{href:Z2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",X:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],M:{dir:g.dn(b.title||"")},W:b.title},{D:"div",I:"ytp-ce-playlist-count",K:[{D:"div",
I:"ytp-ce-playlist-icon"},{D:"div",I:"ytp-ce-playlist-count-text",W:b.playlistLength}]}]}]};c=new g.V(c);break;case "CHANNEL":c={D:"div",X:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],M:{tabindex:"0","aria-label":b.Wj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",
K:[{D:"div",I:"ytp-ce-expanding-overlay-body",K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"a",X:["ytp-ce-channel-title","ytp-ce-link"],M:{href:Z2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.dn(b.title||"")},W:b.title},b.subscribeButton?{D:"div",I:"ytp-ce-subscribe-container",K:[{D:"div",I:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{D:"div",I:"ytp-ce-channel-subscribers-text",W:b.subscribersText}:"",b.metadata?{D:"div",X:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
W:b.metadata}:""]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",M:Y2(b)}]};c=new g.V(c);var d=g.Ed(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.K(d,"ytp-ce-subscribe-button");if(a.player.N().o){var e=null;var f=b.Nb.itct}else e="endscreen",f=null;e=new g.nQ(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.H.push(e)}break;case "WEBSITE":c={D:"div",X:["ytp-ce-element","ytp-ce-website"],M:{tabindex:"0","aria-label":b.Wj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",K:[{D:"div",I:"ytp-ce-expanding-overlay-body",
K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",I:"ytp-ce-website-title",M:{dir:g.dn(b.title||"")},W:b.title},{D:"div",I:"ytp-ce-website-metadata",W:b.metadata},{D:"a",X:["ytp-ce-website-goto","ytp-ce-link"],M:{href:Z2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",M:Y2(b)},{D:"div",I:"ytp-ce-expanding-icon",M:Cqa(b.iconUrl)}]};c=new g.V(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",I:"ytp-ce-merchandise-price-container",
K:[{D:"div",I:"ytp-ce-merchandise-price",W:b.productPrice}]},b.additionalFeesText&&c.K.push({D:"div",I:"ytp-ce-merchandise-additional-fees",W:b.additionalFeesText})),c={D:"div",X:["ytp-ce-element","ytp-ce-merchandise"],M:{tabindex:"0","aria-label":b.Wj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",K:[{D:"div",
I:"ytp-ce-expanding-overlay-body",K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",I:"ytp-ce-merchandise-title",M:{dir:g.dn(b.title||"")},W:b.title},c,{D:"div",I:"ytp-ce-merchandise-metadata",W:b.metadata},{D:"a",X:["ytp-ce-merchandise-goto","ytp-ce-link"],M:{href:Z2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",M:Y2(b)},{D:"div",I:"ytp-ce-merchandise-invideo-cta-container",K:[{D:"div",I:"ytp-ce-merchandise-invideo-cta",
W:b.callToAction}]}]},c=new g.V(c)}b.UF&&g.K(c.element,"ytp-ce-placeholder");return c},Y2=function(a){if(a.rw)var b=a.rw.thumbnails;
return Cqa(b?b[b.length-1].url:null)},Cqa=function(a){return a?{style:"background-image: url("+a+")"}:{}},Bqa=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ia("mouseenter",(0,g.x)(a.Zr,a,b,c));b.ia("mouseleave",(0,g.x)(a.mt,a,b,c));a.player.N().o||b.ia("click",(0,g.x)(function(l){g.K(l.element,"ytp-ce-element-hover")},a,b));
b.ia("click",(0,g.x)(a.kA,a,c));b.ia("keypress",(0,g.x)(a.kA,a,c));b.ia("focus",(0,g.x)(function(l,m){this.Zr(l,m)},a,b,c));
b.ia("blur",(0,g.x)(function(l,m){this.mt(l,m)},a,b,c));
b.ia("touchstart",(0,g.x)(a.Zr,a,b,c));var f=g.Gd("ytp-ce-expanding-overlay-hider",b.element);f&&b.L(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.Hn(b.element,"ytp-ce-element-hover");g.Hn(b.element,"ytp-ce-force-expand")});
b.ia("keydown",(0,g.x)(function(l,m){this.P=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.x)(function(l,m,n){this.G+=n;0<this.G?(g.K(l.element,"ytp-ce-force-expand"),$2(this,m.id,!0)):(g.Hn(l.element,"ytp-ce-force-expand"),g.Hn(l.element,"ytp-ce-element-hover"),$2(this,m.id,!1))},a,b,c);
c=(0,g.x)(function(l,m){m&&(l.ia("blur",g.Oa(function(){"none"!=m.style.display&&a.P&&m.focus()})),l.L(m,"focus",d),l.L(m,"blur",e))},a,b);
c(g.Gd("ytp-sb-subscribe",b.element));c(g.Gd("ytp-sb-unsubscribe",b.element));b.ia("focus",d);b.ia("blur",e)},Z2=function(a,b){var c=a.player.N();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.Yx(c)+b}else return"";return b},$2=function(a,b,c){a.w&&(c?a.C.show():a.C.hide());
for(var d in a.o)d!=b&&g.L(a.o[d].element,"ytp-ce-element-shadow-show",c)},a3=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||0==b.length||W2(a))c&&c();else{b=Dqa(a,b);var e=0,f=!1,k=new g.J(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Mp(b[a],d)}},b3=function(a,b,c){a3(a,b.clickUrls,c);
(a=g.Or())&&b.QF&&g.es(a,b.visualElement)},Dqa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(Eqa(b[e],c));return d},Eqa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Fqa=function(a){return g.Ia(a)&&a.length?a[0]:a},c3=function(a){return"string"===typeof a?a:""},d3=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},Hqa=function(a){var b=Gqa;
if(null==a)return null;if(g.Ja(a)){var c=[];(0,g.y)(a,function(d){(d=b(d))&&c.push(d)});
return c}return(a=b(a))?[a]:[]},Iqa=function(a){this.externalId=a},Jqa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},e3=function(a){if(!a)return null;
var b=g.Bc(c3(a.value));b=g.zc(b);if(!b)return null;var c=d3(a.target,Kqa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Jqa(b,c,"true"==d||"false"==d?"true"==d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},f3=function(a){return a.value?a.value:null},Lqa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},Gqa=function(a){if(!a)return null;
var b=d3(a.type,Mqa),c=d3(a.trigger,Nqa),d=Fqa(a.url);d=e3(d?d:null);a=Fqa(a.subscribeData);var e=a?a:null;e?(a=c3(e.external_user_id),e=c3(e.subscription_token),a=a&&e?new Iqa(a):null):a=null;return b?new Lqa(b,c,d,a):null},Oqa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.o=d||[];this.data=e},Qqa=function(a){return(a=Pqa(a,function(b){return"openUrl"==b.type&&null!=b.url}))?a.url:null},Pqa=function(a,b){return g.Va(a.o,b,void 0)},Rqa=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},Sqa=function(a,b){this.merchant=a;
this.price=b},Tqa=function(a){this.o=a},Uqa=function(a,b,c){b&&(c?g3(a,(0,g.A)(b,g.Oa(function(d,e){return g.bn(e,d)},c))):g3(a,b))},g3=function(a,b,c,d){var e=1,f=-1;
if(c){var k=!1;var l=function(){e--;e||k||(clearTimeout(f),k=!0,c())};
f=setTimeout(function(){k=!0;c()},1E3)}(0,g.y)(b||[],function(m){e++;
g.Mp(m,l)});
d&&(e++,0!=d&&a.o.sendVideoStatsEngageEvent(d,l))},Vqa=function(a,b,c,d,e,f,k){this.o=a;
this.w=b;this.ab=c;this.videoData=d;this.logger=e;this.aa=f;this.u=k},h3=function(a,b){this.o=a;
this.w=b},Yqa=function(a,b){var c=[];
(0,g.y)(b.choices,function(k){c.push(Wqa(b,k))},a);
var d={D:"ul",M:{role:"radiogroup"},K:c},e={};b.ti&&(e["aria-label"]=g.FM("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{D:"div",I:"iv-card-content",K:[i3("h2",e,b.title),{D:"form",K:[{D:"fieldset",K:[d]}]}]}];b.ti&&(f.push("iv-card-unavailable"),d.push({D:"div",X:["iv-card-sign-in"],K:[{D:"h2",W:"Want to vote?"},{D:"a",X:["iv-card-sign-in-button","iv-button"],M:{href:f3(b.ti)},K:[{D:"span",X:["iv-button-content"],W:"Sign in"}]}]}));f=new g.V({D:"div",
X:f,K:d});d=f.element;Xqa(b,d);wqa(a.o.o,d,g.Oa(a.A,b),a);(0,g.y)(g.Fd("iv-card-poll-choice-input",d),function(k){this.o.o.ia(k,"focus",g.Oa(this.u,!0));this.o.o.ia(k,"blur",g.Oa(this.u,!1))},a);
b.ti&&(d=g.Gd("iv-card-sign-in-button",d),a.w(d,b.ti,b.id,b.Nb,b.Gc.click,5));return f},Zqa=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.eP?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.TF&&b.Ov?{D:"span",X:d,M:e,W:b.Ov}:"";c={D:"div",X:["iv-card",c],K:[{D:"a",I:"iv-click-target",M:{href:f3(b.url)},K:[j3(b.zi,d?{D:"div",I:"iv-card-image-text",K:[d,b.priceText]}:""),{D:"div",I:"iv-card-content",K:[{D:"h2",I:"iv-card-primary-link",W:b.title},k3(a,b)]}]}]};c=new g.V(c);l3(a,g.Fd("iv-click-target",c.element),b,b.url);return c},m3=function(a){return a.customMessage?
i3("div","iv-card-message",a.customMessage):""},j3=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{D:"div",I:"iv-card-image",M:{style:c},K:d}},k3=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.y)(b.metaInfo,function(d){c.push(i3("li","",d))},a);
return{D:"ul",I:"iv-card-meta-info",K:c}},Wqa=function(a,b){return{D:"li",
I:Rqa(a,b.index),K:[{D:"label",K:[{D:"input",I:"iv-card-poll-choice-input",M:{type:"checkbox",role:"radio",name:a.id.replace(/[^a-z0-9-]/gi,"-")+b.index.toString(),value:b.index.toString(),"data-poll-choice-index":b.index.toString()}},{D:"span",I:"iv-card-poll-choice-text",K:[{D:"span",I:"iv-card-poll-choice-percent"},i3("span",void 0,b.desc)]}]},{D:"div",I:"iv-card-poll-result",K:[{D:"div",I:"iv-card-poll-result-bar"}]}]}},i3=function(a,b,c){b?"string"===typeof b?b={"class":b}:g.Ia(b)&&(b={"class":b.join(" ")}):
b={};
b.dir=g.dn(c);return{D:a,M:b,W:c}},$qa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Hm&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Hm+");");c.dir=g.dn(a.customMessage);var d=[{D:"span",W:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",I:"iv-card-link-icon"}));return{D:"div",X:b,M:c,K:d}},Xqa=function(a,b){var c=0;
(0,g.y)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Gd(Rqa(a,e.index),b);e=e.count/c;null==a.Ce&&(e=0);g.L(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.Ce==d);f.getElementsByTagName("input")[0].checked=a.Ce==d;var k=Math.floor(100*e).toFixed(0),l=g.Gd("iv-card-poll-choice-percent",f);g.ae(l,g.FM("$PERCENT%",{PERCENT:k}));f=g.Gd("iv-card-poll-result-bar",f);g.qh(f,"transform","scaleX("+e.toFixed(2)+")")}g.L(b,"iv-card-poll-voted",null!=a.Ce);g.L(b,"iv-card-poll-expanded",
null!=a.Ce&&1<a.choices.length)},l3=function(a,b,c,d){d&&(0,g.y)(b,function(e){this.w(e,d,c.id,c.Nb,c.Gc.click,5)},a)},ara=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},bra=function(a,b){return b?b:ara(a)?"current":"new"},n3=function(a,b){g.B.call(this);
this.o=a;this.context=b;this.zu=!1},cra=function(a,b,c,d,e){var f=f3(b);
if(f){var k=bra(f,b.target),l=(0,g.x)(function(){b.o&&this.context.aa.pauseVideo();var m=this.context.videoData.uc||!1,n=g.ap(f||"");m&&n&&(n.v||n.list)?g.HT(this.context.aa.app,n.v,c,n.list,!1,void 0):g.JM(f||"","current"==k?"_top":void 0,c)},a);
"new"==k&&(l(),l=null);g3(a.context.logger,d,l,e);ara(f)||(a=g.Or(),d=c.itct,a&&d&&g.es(a,g.Dr(d)))}},dra=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},o3=function(a,b,c){return{Kx:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
WB:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
mp:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl})}},r3=function(a,b,c){n3.call(this,b,c);
var d=this;this.w=a;this.da=this.Aa=this.C=this.za=!1;this.ea=null;this.Z=new g.J(g.Fa,c.ab.Qa?4E3:3E3);g.H(this,this.Z);this.sa=new g.J(g.Fa);g.H(this,this.sa);this.H=new h3(c,(0,g.x)(this.Gj,this),(0,g.x)(this.On,this));this.U=new g.V({D:"div",I:"iv-drawer",M:{id:"iv-drawer"},K:[{D:"div",I:"iv-drawer-header",M:{"aria-role":"heading"},K:[{D:"span",I:"iv-drawer-header-text"},{D:"button",X:["iv-drawer-close-button","ytp-button"],M:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",I:"iv-drawer-content"}]});
g.H(this,this.U);this.F=this.U.element;this.ra=new g.$L(this.U,330);g.H(this,this.ra);this.ya=g.Gd("iv-drawer-header-text",this.F);this.B=g.Gd("iv-drawer-content",this.F);this.A=[];this.xa=this.S=this.G=this.ga=this.u=null;this.V=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.Aa&&p3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Aa=d.C)&&q3(d)});
this.O=this.J=this.ca=null;this.P=0},era=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){p3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){q3(a)});
var c=b.data.headerText;g.ae(a.ya,c);a.S&&a.S.setAttribute("title",c);a.ca=g.Dr(b.data.trackingParams);a.O=g.Dr(b.data.closeTrackingParams);a.J=g.Dr(b.data.iconTrackingParams)},fra=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.P;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.P,type:"simple",teaserText:g.cA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Nb:s3(a,c,b,d),sponsored:!1,Gc:o3(d,e,d.command),Yd:d.trackingParams?g.Dr(d.trackingParams):null,Td:e.trackingParams?
g.Dr(e.trackingParams):null,pd:f&&f.trackingParams?g.Dr(f.trackingParams):null,imageUrl:t3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.cA(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Hm:null,title:d.title?g.cA(d.title):"",customMessage:d.callToAction?g.cA(d.callToAction):"",url:d.command.urlEndpoint.url?e3({pause_on_navigation:!a.context.videoData.ua,target:"new",value:d.command.urlEndpoint.url}):null};u3(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.P,type:"collaborator",teaserText:g.cA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Nb:s3(a,c,b,d),sponsored:!1,Gc:o3(d,e,d.endpoint),Yd:d.trackingParams?g.Dr(d.trackingParams):null,Td:e.trackingParams?g.Dr(e.trackingParams):null,pd:f&&f.trackingParams?
g.Dr(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.cA(d.customText):null,ZA:t3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.cA(d.channelName):"",metaInfo:[d.subscriberCountText?g.cA(d.subscriberCountText):""],url:e3({pause_on_navigation:!a.context.videoData.ua,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};u3(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.P,type:"playlist",teaserText:g.cA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Nb:s3(a,c,b,d),sponsored:!1,Gc:o3(d,e,d.action),Yd:d.trackingParams?g.Dr(d.trackingParams):null,Td:e.trackingParams?g.Dr(e.trackingParams):null,pd:f&&f.trackingParams?g.Dr(f.trackingParams):
null,zi:t3(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.cA(d.customMessage):null,playlistVideoCount:g.cA(d.playlistVideoCount),title:d.playlistTitle?g.cA(d.playlistTitle):"",metaInfo:[d.channelName?g.cA(d.channelName):"",d.videoCountText?g.cA(d.videoCountText):""],url:e3({pause_on_navigation:!a.context.videoData.ua,target:"new",value:dra(d.action)})};u3(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.P,type:"video",teaserText:g.cA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Nb:s3(a,c,b,d),sponsored:!1,Gc:o3(d,e,d.action),Yd:d.trackingParams?g.Dr(d.trackingParams):null,Td:e.trackingParams?g.Dr(e.trackingParams):null,pd:f&&f.trackingParams?g.Dr(f.trackingParams):null,zi:t3(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.cA(d.lengthString):null,customMessage:d.customMessage?g.cA(d.customMessage):null,title:d.videoTitle?g.cA(d.videoTitle):"",metaInfo:[d.channelName?g.cA(d.channelName):"",d.viewCountText?g.cA(d.viewCountText):""],isLiveNow:!!d.badge,url:e3({pause_on_navigation:!a.context.videoData.ua,target:"new",value:dra(d.action)})};u3(a,c)}a.P++},t3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height==b||290==a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},s3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId,itct:d.trackingParams}},hra=function(a,b){var c=gra(a,b);
c&&(c==a.u&&(a.u=null),a.w.removeCueRange(c.card.id),g.Xd(c.iq),g.cb(a.A,c),a.Jm(),v3(a))},p3=function(a,b,c){if(!a.C){a.ra.show();
a.ga=new g.J(function(){g.K(g.mL(a.context.aa),"ytp-iv-drawer-open")},0);
a.ga.start();a.ea=g.Bq(a.B,"mousewheel",(0,g.x)(a.TG,a));a.C=!0;var d=g.Or();d&&a.ca&&a.O&&K2(d,[a.ca,a.O]);var e={TRIGGER_TYPE:b};(0,g.y)(a.A,function(f){f.py||(f.py=!0,Uqa(a.context.logger,f.card.Gc.Kx,e));d&&K2(d,[f.card.Yd])});
J2(a.w);c&&(a.G=new g.J(function(){a.na=a.S;a.xa.focus()},330),a.G.start())}},q3=function(a){a.C&&(a.ra.hide(),g.Cq(a.ea),a.ea=null,g.Hn(g.mL(a.context.aa),"ytp-iv-drawer-open"),a.C=!1,J2(a.w),a.G&&a.G.stop(),a.G=new g.J(function(){a.na&&(a.na.focus(),a.na=null)},330),a.G.start())},ira=function(a){var b=g.Gd("iv-drawer-close-button",a.F);
a.context.o.ia(b,"click",a.YD,a);a.context.o.ia(a.B,"touchend",function(){a.Z.start()});
a.context.o.ia(a.B,"scroll",a.lE,a);a.context.u.subscribe("onHideControls",function(){a.da=!0});
a.context.u.subscribe("onShowControls",function(){a.da=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.da=g.Fn(g.mL(a.w),"ytp-autohide")});
a.V.push(g.Ko("iv-button-shown",a.bG,a));a.V.push(g.Ko("iv-button-hidden",a.aG,a));a.V.push(g.Ko("iv-teaser-shown",a.eG,a));a.V.push(g.Ko("iv-teaser-hidden",a.dG,a));a.V.push(g.Ko("iv-teaser-clicked",a.cG,a))},u3=function(a,b){a.za||(g.Gn(a.o,["html5-stop-propagation",
"iv-drawer-manager"]),g.GL(a.w,a.F,5),ira(a),a.S=g.Gd("ytp-cards-button",g.mL(a.w)),a.xa=g.Gd("iv-drawer-close-button",a.F),a.za=!0);hra(a,b.id);var c=jra(a,b);if(c){var d={card:b,iq:c.element,py:!1},e=kra(a,d);g.jb(a.A,e,0,d);c.ba(a.B,e);a.Jm();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Oa(a.wO,d)):(c=1E3*a.context.aa.getCurrentTime(),5E3>c&&c>b.startMs&&a.DB(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Oa(a.DB,d)),v3(a))}},jra=function(a,b){switch(b.type){case "simple":var c=a.H;
var d=b.displayDomain?{D:"div",I:"iv-card-image-text",W:b.displayDomain}:"";var e=$qa(b);d={D:"div",X:["iv-card"],K:[{D:"a",I:"iv-click-target",M:{href:f3(b.url)},K:[j3(b.imageUrl,d),{D:"div",I:"iv-card-content",K:[i3("h2",void 0,b.title),e]}]}]};d=new g.V(d);l3(c,g.Fd("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.H,d={D:"div",X:["iv-card","iv-card-channel"],K:[{D:"a",X:["iv-click-target"],M:{href:f3(b.url),"data-ytid":b.channelId},K:[j3(b.ZA),{D:"div",I:"iv-card-content",
K:[m3(b),{D:"h2",I:"iv-card-primary-link",W:b.title},k3(c,b)]}]}]},d=new g.V(d),l3(c,g.Fd("iv-click-target",d.element),b,b.url),d;case "episode":return Zqa(a.H,b,"iv-card-episode");case "movie":return Zqa(a.H,b,"iv-card-movie");case "playlist":return c=a.H,d={D:"div",X:["iv-card","iv-card-playlist"],K:[{D:"a",I:"iv-click-target",M:{href:f3(b.url)},K:[j3(b.zi,{D:"div",I:"iv-card-image-overlay",K:[{D:"span",I:"iv-card-playlist-video-count",W:b.playlistVideoCount}]}),{D:"div",I:"iv-card-content",K:[m3(b),
i3("h2","iv-card-primary-link",b.title),k3(c,b)]}]}]},d=new g.V(d),l3(c,g.Fd("iv-click-target",d.element),b,b.url),d;case "poll":return Yqa(a.H,b);case "productListing":c=a.H;var f=!g.$a(b.offers);d=["iv-card"];e="";var k=$qa(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",f=b.offers[0],k=[],f.price&&k.push({D:"div",I:"iv-card-offer-price",W:f.price}),f.merchant&&k.push({D:"div",I:"iv-card-offer-merchant",W:f.merchant}),k={D:"div",K:k});d={D:"div",X:d,M:{tabindex:"0"},K:[{D:"a",
X:["iv-card-image","iv-click-target"],M:{style:"background-image: url("+b.imageUrl+");",href:f3(b.url),"aria-hidden":"true",tabindex:"-1"}},{D:"div",I:"iv-card-content",K:[b.sponsored?{D:"div",I:"iv-card-sponsored",K:["Sponsored",{D:"div",I:"iv-ad-info-container",K:[{D:"div",I:"iv-ad-info",W:"{{adInfo}}"},{D:"div",I:"iv-ad-info-icon-container",K:[{D:"div",I:"iv-ad-info-icon"},{D:"div",I:"iv-ad-info-callout"}]}]}]}:"",{D:"a",I:"iv-click-target",M:{href:f3(b.url)},K:[i3("h2",e,b.title),k]}]}]};d=new g.V(d);
e=g.Sd("span");g.ae(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.ub(e,"adInfo");l3(c,g.Fd("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.H,d=b.isLiveNow?{D:"span",X:["yt-badge","yt-badge-live"],W:"LIVE NOW"}:"",d={D:"div",X:["iv-card","iv-card-video"],K:[{D:"a",I:"iv-click-target",M:{href:f3(b.url)},K:[j3(b.zi,b.videoDuration?{D:"span",I:"iv-card-video-duration",W:b.videoDuration}:""),{D:"div",I:"iv-card-content",
K:[m3(b),i3("h2","iv-card-primary-link",b.title),k3(c,b),d]}]}]},d=new g.V(d),l3(c,g.Fd("iv-click-target",d.element),b,b.url),d}return null},kra=function(a,b){if(0==a.A.length)return 0;
var c=g.Wa(a.A,function(d){return b.card.startMs>d.card.startMs||b.card.startMs==d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1==c?0:c+1},lra=function(a){return a.u?"productListing"==a.u.card.type:(0,g.pi)(a.A,function(b){return"productListing"==b.card.type})},v3=function(a){g.L(g.mL(a.w),"ytp-cards-shopping-active",lra(a))},mra=function(a,b){if(a.U.Fa()){var c=new P2([0,
a.B.scrollTop],[0,b.iq.offsetTop],600,qqa);a.context.w.ia(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.w.ia(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.BC(a.U,!0),a.B.scrollTop=b.iq.offsetTop,g.BC(a.U,!1)},w3=function(a){return a.u&&a.u.card?a.u.card:a.A[0]&&a.A[0].card?a.A[0].card:null},gra=function(a,b){return g.Va(a.A,function(c){return c.card.id==b})},x3=function(a,b,c){n3.call(this,a,b);
this.annotation=c;this.isActive=!1},nra=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},y3=function(a,b,c){x3.call(this,a,b,c);
this.w=null;this.G=!1;this.A=null;this.B=!1;this.u=this.F=this.C=null},z3=function(a,b,c){x3.call(this,a,b,c);
this.J=this.C=this.P=!1;this.G=5E3;this.B=null;this.H=g.Rd("DIV","iv-promo-contents");this.w=this.A=this.u=null;this.F=new g.J(function(){this.u.setAttribute("aria-hidden",!0);g.Lh(this.A,!1);g.Lh(this.w,!0)},700,this);
g.H(this,this.F)},ora=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.o.setAttribute("aria-hidden",!0);a.o.setAttribute("aria-label","Promotion");a.o.tabIndex=0;var e=Qqa(a.annotation),f=b.image_url;if(f){var k=g.Rd("DIV",["iv-promo-img","iv-click-target"]);f=g.Rd("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.Rd("SPAN","iv-promo-video-duration",b.video_duration),
k.appendChild(f)):b.playlist_length&&(f=g.Rd("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.Gj(k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=g.Rd("A","iv-promo-txt"),g.Wc(f,f3(e)),a.u=f):a.u=g.Rd("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Rd("P",null,g.Rd("STRONG",null,b.text_line_1));var m=g.Rd("P",null,g.Rd("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");g.R(a.context.ab.experiments,
"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.Rd("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Rd("BUTTON",["iv-button","iv-promo-button"],g.Rd("SPAN","iv-button-content",f));var q=g.Rd("DIV","iv-promo-button-container");q.appendChild(f);e&&a.Gj(a.o,e,a.annotation.id,b.session_data,void 0,c)}g.K(a.u,"iv-click-target");e&&a.Gj(a.u,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=g.Rd("P",null,g.Rd("SPAN",null,b.text_line_1)),
m=g.Rd("P",null,g.Rd("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Rd("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.K(a.u,"iv-click-target"),e&&a.Gj(a.u,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.u.appendChild(l);m&&a.u.appendChild(m);a.H.appendChild(a.u);q&&a.H.appendChild(q);c=g.Rd("DIV","iv-promo-actions");a.w=g.Rd("BUTTON",["iv-promo-expand","ytp-button"]);a.w.title="Expand";a.context.o.ia(a.w,"click",g.Oa(a.fr,5E3),a);c.appendChild(a.w);g.Lh(a.w,!1);
a.context.o.ia(a.o,"mouseover",a.jF,a);a.context.o.ia(a.o,"mouseout",a.iF,a);a.context.o.ia(a.o,"touchend",g.Oa(a.fr,5E3),a);a.A=g.Rd("BUTTON",["iv-promo-close","ytp-button"]);a.A.title="Close";a.context.o.ia(a.A,"click","cta"==a.annotation.style&&b.text_line_3?a.bF:a.aF,a);c.appendChild(a.A);g.Gn(a.o,d);k&&(a.o.appendChild(k),n&&k.appendChild(n));a.o.appendChild(a.H);a.o.appendChild(c)},pra=function(a){a.C||a.J||a.B||(g.K(a.o,"iv-promo-collapsed"),a.C=!0,a.F.start())},qra=function(a){a.F.stop();
a.C&&(g.In(a.o,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.C=!1,a.u&&a.u.removeAttribute("aria-hidden"),g.Lh(a.w,!1),g.Lh(a.A,!0))},rra=function(a,b){a.B||(a.B=g.yf(function(){A3(this);
pra(this)},b,a))},A3=function(a){a.B&&(g.v.clearTimeout(a.B),a.B=null)},B3=function(a){g.HP.call(this,a);
this.J=!1;this.H=0;this.F={};this.U=new Tqa(a);this.B=new g.P(this);g.H(this,this.B);this.C=this.w=null;this.B.L(this.player,"onVideoAreaChange",(0,g.x)(this.R,this,"onVideoAreaChange"));this.B.L(this.player,"onHideControls",(0,g.x)(this.R,this,"onHideControls"));this.B.L(this.player,"onShowControls",(0,g.x)(this.R,this,"onShowControls"));this.B.L(this.player,"resize",(0,g.x)(this.R,this,"resize"));this.B.L(this.player,"presentingplayerstatechange",(0,g.x)(this.R,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.eM,this);this.subscribe("resize",this.Io,this);this.player.N().F.subscribe("vast_info_card_add",this.LA,this);this.S=new g.P(this);g.H(this,this.S);this.O=g.Rd("DIV","video-custom-annotations");this.u=new g.V({D:"div",X:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.u);g.GL(this.player,this.u.element,4);this.u.hide();this.A=new g.V({D:"div",X:["ytp-iv-video-content"]});g.H(this,this.A);g.Ud(this.A.element,g.Rd("DIV","video-annotations",
this.O));this.G=this.o=null;this.P=[];sra(this)&&this.load();var b=g.Sd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.ie(this,function(){g.Xd(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},tra=function(){var a=g.Rd("DIV",["annotation",
"annotation-type-custom"]);g.Lh(a,!1);return a},ura=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},sra=function(a){var b=a.player.N();
a=a.player.getVideoData();return 1==(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.yC||b.F.get(a.videoId)||g.R(b.experiments,"allow_skip_annotations_invideo")&&(g.JB(a)||g.KB(a))?!0:!1},vra=function(a,b,c){a.J=!0;
a.C=g.sp(b,c)},wra=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.La(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(wra(a,e))}return c},xra=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},Ara=function(a){var b=a.player.getVideoData();
if(b.Xd){var c=a.player.N().F.get(b.videoId);if(c){var d={format:"XML",Wd:{},method:"POST",withCredentials:!0};d.wd=(0,g.x)(function(e,f,k){xra(this,e,f)||(e=g.mp(k)&&k.responseXML?k.responseXML:null)&&C3(this,e)},a,a.H,b.videoId);
g.Hp()&&(d.wd=yra(a,d.wd));d.zb={ic_only:"1"};zra(d,c);a.J=!0;g.sp(b.Xd,d)}}},zra=function(a,b){a.method="POST";
a.zb=a.zb||{};b.Nm&&(a.zb.ic_coll=b.Nm);b.Om&&(a.zb.ic_xml=b.Om);b.Zl&&(a.zb.ic_track=b.Zl)},Bra=function(a){var b=new g.V({D:"div"});
g.Lh(b.element,!1);var c=new r3(a.player,b.element,D3(a));g.H(c,b);b.ba(a.u.element);c.Nl();return c},D3=function(a){if(!a.G){var b=new S2(a);
g.H(a,b);var c=new g.U1(a);g.H(a,c);a.G=new Vqa(b,c,a.player.N(),a.player.getVideoData(),a.U,a.player,a.jc)}return a.G},C3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Or();if(e){var f=g.Mr();f&&g.cs(e,f,[g.Dr(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var k=wra(a,d[e]);f=null;try{if(k){var l=k.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var q=d3(k.type,Cra),t=d3(k.style,Dra),u=c3(k.data),z=0!=u.length?JSON.parse(u):{},C=Hqa(k.action);f=n&&q?new Oqa(n,q,t,C,z):null}else f=null}catch(ka){}if(f){a:{switch(f.type){case "branding":case "promotion":k=!0;break a}k=
!1}if(k){k=a;m=f;var D=tra(),E=null;switch(m.type){case "branding":if(k.player.N().Oa)break;k.u.element.appendChild(D);E=new y3(D,D3(k),m);break;case "promotion":g.GL(k.player,D,4),E=new z3(D,D3(k),m)}E&&E.Nl();if(k=E)g.H(a,k),a.F[f.id]=k}else if("card"==f.type||"drawer"==f.type){a.o||(a.o=Bra(a),g.H(a,a.o));if("card"==f.type){if(c=a.o,E=f&&f.data&&f.data.card_type)switch(k=f.data.tracking||{},k={Kx:k.impression,click:k.click,close:k.close,WB:k.teaser_impression,mp:k.teaser_click},m=f.data.tracking_params||
{},D=null,E){case "collaborator":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Gc:k,Yd:m.card?g.Dr(m.card):null,Td:m.teaser?g.Dr(m.teaser):null,pd:m.icon?g.Dr(m.icon):null,channelId:f.data.channel_id,customMessage:f.data.custom_message?f.data.custom_message:null,ZA:f.data.image_url,title:f.data.title,
metaInfo:f.data.meta_info,url:e3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};u3(c,f);break;case "episode":case "movie":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Gc:k,Yd:m.card?g.Dr(m.card):null,Td:m.teaser?g.Dr(m.teaser):null,pd:m.icon?g.Dr(m.icon):
null,zi:f.data.image_url,Ov:f.data.badge_symbol||"",priceText:f.data.price_text||"",title:f.data.title,metaInfo:f.data.meta_info,TF:!!f.data.is_paygated,eP:!!f.data.user_has_entitlement,url:e3({target:f.data.target||"new",value:f.data.url})};u3(c,f);break;case "playlist":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||
!1,Gc:k,Yd:m.card?g.Dr(m.card):null,Td:m.teaser?g.Dr(m.teaser):null,pd:m.icon?g.Dr(m.icon):null,zi:f.data.image_url,playlistVideoCount:f.data.playlist_video_count,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,url:e3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};u3(c,f);break;case "poll":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,
startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Gc:k,Yd:m.card?g.Dr(m.card):null,Td:m.teaser?g.Dr(m.teaser):null,pd:m.icon?g.Dr(m.icon):null,title:f.data.title,choices:f.data.choices,Ce:f.data.hasOwnProperty("old_vote")?f.data.old_vote:null,ti:f.data.signin_url?e3({target:"current",value:f.data.signin_url}):null,pP:f.data.hasOwnProperty("xsrf_token")?f.data.xsrf_token:null};u3(c,f);break;case "productListing":f.data.signin_url&&(D=e3({target:"current",
value:f.data.signin_url}));E=[];for(var G=f.data.offers||[],F=0;F<G.length;F++)E.push(new Sqa(g.cd(G[F].merchant),g.cd(G[F].price)));f={sT:!1,id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Gc:k,Yd:m.card?g.Dr(m.card):null,Td:m.teaser?g.Dr(m.teaser):null,pd:m.icon?g.Dr(m.icon):null,imageUrl:f.data.image_url,
displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,Hm:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:e3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url}),ti:D,GT:f.data.signin_title?f.data.signin_title:null,FT:f.data.signin_message?f.data.signin_message:null,offers:E};u3(c,f);break;case "simple":f={id:f.id,timestamp:f.data.timestamp||
0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Gc:k,Yd:m.card?g.Dr(m.card):null,Td:m.teaser?g.Dr(m.teaser):null,pd:m.icon?g.Dr(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,Hm:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,
customMessage:f.data.custom_message?f.data.custom_message:null,url:e3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};u3(c,f);break;case "video":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Gc:k,Yd:m.card?g.Dr(m.card):null,Td:m.teaser?g.Dr(m.teaser):
null,pd:m.icon?g.Dr(m.icon):null,zi:f.data.image_url,videoDuration:f.data.video_duration||null,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,isLiveNow:!!f.data.is_live_now,url:e3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})},u3(c,f)}}else era(a.o,f);c=!0}}}c&&(J2(a.player),a.Io())},Era=function(a,b){var c=!1;
a.o||(a.o=Bra(a),g.H(a,a.o));for(var d=g.p(b.cards||[]),e=d.next();!e.done;e=d.next())fra(a.o,e.value.cardRenderer),c=!0;c&&(c=a.o,d=b.headerText?g.cA(b.headerText):"",g.ae(c.ya,d),c.S&&c.S.setAttribute("title",d),c.ca=b.trackingParams?g.Dr(b.trackingParams):null,c.O=b.closeButton.infoCardIconRenderer.trackingParams?g.Dr(b.closeButton.infoCardIconRenderer.trackingParams):null,c.J=b.icon.infoCardIconRenderer.trackingParams?g.Dr(b.icon.infoCardIconRenderer.trackingParams):null,J2(a.player),a.Io())},
Fra=function(a,b,c,d,e){if(!a.player.N().Oa){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new Lqa("openUrl","click",new Jqa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;k=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.cA(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(k=g.cA(b.subscriberCountText))):(b.subscriberCountText&&(e=g.cA(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(k=g.cA(b.subscriberCountWithSubscribeText)));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.cA(b.unsubscribedButtonText),subscribeCount:e,unsubscribeText:g.cA(b.subscribedButtonText),unsubscribeCount:k,enabled:b.enabled,classic:!1,subscribed:b.subscribed,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new Oqa(c,"branding","branding",f,d);d=tra();a.u.element.appendChild(d);f=new y3(d,D3(a),f);f.Nl();g.H(f,f);a.F[c]=f}},yra=function(a,b){return(0,g.x)(function(){if(!this.la()){var c=
Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Oa.apply(window,c);this.P.push(g.Fp(b))}},a)},M2={},N2=null;g.Qa(P2,g.Jn);g.h=P2.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.w;else if(1==this.o)return!1;O2(this);this.startTime=a=(0,g.I)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.F=this.startTime;this.progress||this.B();this.qe("play");-1==this.o&&this.qe("resume");this.o=1;var b=g.Na(this);b in M2||(M2[b]=this);sqa();tqa(this,a);return!0};
g.h.stop=function(a){O2(this);this.o=0;a&&(this.progress=1);uqa(this,this.progress);this.qe("stop");this.A()};
g.h.pause=function(){1==this.o&&(O2(this),this.o=-1,this.qe("pause"))};
g.h.Y=function(){0==this.o||this.stop(!1);this.qe("destroy");P2.Gb.Y.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.ht=function(){this.qe("animate")};
g.h.qe=function(a){this.dispatchEvent(new vqa(a,this))};
g.Qa(vqa,g.le);g.Qa(Q2,P2);Q2.prototype.C=g.Fa;Q2.prototype.ht=function(){this.C();Q2.Gb.ht.call(this)};
Q2.prototype.A=function(){this.C();Q2.Gb.A.call(this)};
Q2.prototype.B=function(){this.C();Q2.Gb.B.call(this)};
g.Qa(R2,Q2);R2.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.r(S2,g.B);S2.prototype.ia=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.Bq(a,b,c);this.o.push(a);return a};
S2.prototype.Mr=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.Lq(a,b,c);this.o.push(a);return a};
S2.prototype.Wa=function(a){g.Cq(a);g.cb(this.o,a)};
S2.prototype.Y=function(){g.Cq(this.o);this.o.length=0;g.B.prototype.Y.call(this)};g.r(V2,g.HP);g.h=V2.prototype;g.h.load=function(){g.HP.prototype.load.call(this);if(!W2(this)){var a=g.IB(this.player.getVideoData());if(a)a=U2(a,yqa(this)),X2(this,a,!1);else{var b=this.player.getVideoData();a=b.videoId;this.A&&this.A.abort();a={method:"POST",wd:(0,g.x)(this.QK,this,a),Wd:{v:a},withCredentials:!0};this.J&&(a.Wd.ptype="embedded");var c=this.player.getVideoData().Zm;c&&(a.zb={ad_tracking:c});if(b=g.HB(b))if(b=g.Bc(b),b=g.zc(b))this.A=g.sp(b,a)}}};
g.h.unload=function(){X2(this,null);this.A&&(this.A.abort(),this.A=null);g.HP.prototype.unload.call(this)};
g.h.Mc=function(a,b){if(!W2(this))return null;if("loadCustomEndscreenRenderer"==a){var c=U2(b,"new");X2(this,c);return!0}return null};
g.h.getOptions=function(){return W2(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.QK=function(a,b){var c=this.A=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=U2(c,yqa(this)))}X2(this,c)};
g.h.Fy=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Gra.length;f++){var k=Math.abs(b.width-Gra[f]);if(-1==e||d>=k)e=f,d=k}d=Hra[e];this.w&&g.qh(this.w.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],k=this.F[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Jh(e.element,Math.round(k.width*a.width),f);g.yh(e.element,m,n);g.In(e.element,Ira);m=k.left+k.width/2;k=k.top+l/2;g.K(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.In(e.element,Hra);g.K(e.element,d);(e=g.Ed(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.qh(e,"height",f+"px")}}}}};
g.h.zG=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())a3(this,this.u.impressionUrls),(a=g.Or())&&this.u.visualElement&&g.ds(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.F[a];g.K(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");g.K(g.mL(this.player),"ytp-ce-shown");a3(this,c.impressionUrls);(b=g.Or())&&g.ds(b,c.visualElement);this.player.N().Eb&&this.player.ka("endscreenelementshown",a)}};
g.h.AG=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.Hn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);g.Hn(g.mL(this.player),"ytp-ce-shown");this.player.N().Eb&&this.player.ka("endscreenelementhidden",a)}};
g.h.GN=function(a){var b=this;a.target===window&&(new g.J(function(){for(var c in b.o)g.In(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.kA=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Fn(c,"ytp-ce-element");){g.Fn(c,"subscribe-label")&&b3(this,a);if(g.Fn(c,"ytp-ce-channel-subscribe"))return;c=g.Zd(c)}if(!c||g.Fn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.mt(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.KO?(b3(this,a),this.CB(),this.player.pauseVideo(),c=g.Bc(Z2(this,a.targetUrl)),c=g.zc(c),g.JM(c,void 0,a.Nb)):(c=this.player.getVideoData().uc,
c=(0,g.x)(this.EO,this,c,Z2(this,a.targetUrl),a.Nb),c=(0,g.x)(this.CB,this,c),b3(this,a,c))}}};
g.h.EO=function(a,b,c){var d=g.ap(b);a&&d&&(d.v||d.list)?g.HT(this.player.app,d.v,c,d.list,!1,void 0):g.IM(b,c)};
g.h.Zr=function(a,b){g.Fn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.K(a.element,"ytp-ce-element-hover"):this.player.N().o?(new g.J(function(){g.K(a.element,"ytp-ce-element-hover")},200)).start():g.K(a.element,"ytp-ce-element-hover"),a3(this,b.GF),$2(this,b.id,!0))};
g.h.mt=function(a,b){g.Hn(a.element,"ytp-ce-element-hover");g.Hn(a.element,"ytp-ce-force-expand");$2(this,b.id,!1)};
g.h.CB=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var Gra=[346,426,470,506,570,640,853,1280,1920],Hra="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Ira=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var Kqa={uQ:"current",PR:"new"};var Mqa={CLOSE:"close",SR:"openUrl",uD:"subscribe"},Nqa={oQ:"click",CLOSE:"close",fR:"hidden",xS:"rollOut",yS:"rollOver",BS:"shown"};var Dra={RP:"anchored",OC:"branding",CHANNEL:"channel",tQ:"cta",hR:"highlightText",yR:"label",PLAYLIST:"playlist",kS:"popup",FS:"speech",uD:"subscribe",PS:"title",VIDEO:"video",dT:"website"},Cra={OC:"branding",fQ:"card",AQ:"drawer",gR:"highlight",FR:"marker",pS:"promotion",TEXT:"text",fT:"widget"};h3.prototype.u=function(a,b){var c=g.fe(b.target,"label");c&&g.L(c,"iv-card-poll-choice-focused",a)};
h3.prototype.A=function(a,b){var c=g.fe(b.target,null,"iv-card-poll",void 0);if(c)if(a.ti)g.Gd("iv-card-sign-in-button",c).click();else{var d=parseInt(oqa(b.target),10);if(null==a.Ce)a.choices[d].count++,a.Ce=d;else if(a.Ce!=d){var e=a.choices[a.Ce];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.Ce=d}else e=a.choices[a.Ce],e.count=Math.max(e.count-1,0),a.Ce=null;Xqa(a,c);g.wp(this.o.videoData.Xd,{Wd:{action_poll_vote:1},zb:{poll_id:a.id,index:d,session_token:a.pP}});g3(this.o.logger,a.Gc.click,
void 0,5);(c=g.Or())&&a.Yd&&g.es(c,a.Yd)}};g.r(n3,g.B);g.h=n3.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.OD(a,b,{id:c});g.H(this,a);a.namespace="annotations_module";d&&nqa(a).subscribe("onEnter",d,this);e&&nqa(a).subscribe("onExit",e,this);g.CL(this.context.aa,[a])};
g.h.Nl=function(){this.context.u.subscribe("resize",this.Jm,this)};
g.h.Gj=function(a,b,c,d,e,f){this.context.o.ia(a,"click",g.Oa(this.On,b,c,d,e||[],f||0),this);this.context.o.ia(a,"touchstart",g.Oa(function(){this.zu=!1}),this);
this.context.o.ia(a,"touchmove",g.Oa(function(){this.zu=!0}),this)};
g.h.On=function(a,b,c,d,e,f){if(this.zu)return!1;f&&(f.stopPropagation(),f.preventDefault());cra(this,a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.Xd(this.o)};
g.h.Jm=function(){};g.r(r3,n3);g.h=r3.prototype;g.h.isAvailable=function(){var a;if(a=!!this.A.length)(a=g.mL(this.w))?(a=g.Kh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Jm=function(){var a=this.isAvailable();g.Lh(this.o,a);g.L(g.mL(this.context.aa),"ytp-iv-drawer-enabled",a);J2(this.w)};
g.h.destroy=function(){var a=g.uL(g.hL(this.w));a&&a.Yr(!1,void 0);try{g.mL(this.w).removeChild(this.F)}catch(b){}g.Lo(this.V);g.Cq(this.ea);this.ga&&this.ga.dispose();this.G&&this.G.dispose();n3.prototype.destroy.call(this)};
g.h.TG=function(a){this.Z.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.B.scrollTop+=a};
g.h.DB=function(a){if(!g.Fn(g.mL(this.w),"ytp-cards-teaser-shown")){if(this.u!=a){var b=g.Or(),c=this.u?this.u.card.pd:this.J;b&&c&&L2(b,[c]);this.u=a;v3(this)}if(b="none"!=this.o.style.display)2==this.context.aa.getPresentingPlayerType()?b=1==this.context.aa.getAdState():(b=this.context.aa.getPlayerState(),c=0==b&&0===this.context.aa.getCurrentTime(),b=1==b||3==b||c);b&&a.card.teaserDurationMs&&(b={teaserText:a.card.teaserText,durationMs:a.card.teaserDurationMs},(c=g.uL(g.hL(this.w)))&&c.Yr(!0,b));
this.sa.isActive()||((!this.C||!this.Z.isActive()&&this.da)&&mra(this,a),this.sa.start(910+a.card.teaserDurationMs))}};
g.h.wO=function(a){this.C||(this.u=a,v3(this),mra(this,a),p3(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1))};
g.h.YD=function(){if(this.C){g3(this.context.logger,w3(this).Gc.close);var a=g.Or();a&&this.O&&g.es(a,this.O);q3(this)}};
g.h.lE=function(){g.L(this.F,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.h.bG=function(){var a=g.Or(),b=w3(this);b=b?b.pd:this.J;a&&b&&K2(a,[b])};
g.h.aG=function(){var a=g.Or(),b=w3(this);b=b?b.pd:this.J;a&&b&&L2(a,[b])};
g.h.eG=function(){var a=w3(this);g3(this.context.logger,a.Gc.WB);var b=g.Or();b&&a&&K2(b,[a.Td,a.pd])};
g.h.dG=function(){var a=g.Or(),b=w3(this);a&&b&&L2(a,[b.Td])};
g.h.cG=function(a){var b=w3(this),c=g.Or();this.u?a?(a=this.context.logger,g3(a,b.Gc.mp),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.Td&&g.es(c,b.Td)):(a=this.context.logger,g3(a,b.Gc.mp),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.pd&&g.es(c,b.pd)):(a=this.context.logger,g3(a,b.Gc.mp),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.J&&g.es(c,this.J))};g.r(x3,n3);x3.prototype.Nl=function(){n3.prototype.Nl.call(this);nra(this)};
x3.prototype.show=function(){n3.prototype.show.call(this);var a=g.Or(),b=this.annotation.data;a&&b&&(b=b.session_data)&&K2(a,[g.Dr(b.itct)])};
x3.prototype.hide=function(){n3.prototype.hide.call(this);var a=g.Or(),b=this.annotation.data;a&&b&&(b=b.session_data)&&L2(a,[g.Dr(b.itct)])};g.r(y3,x3);g.h=y3.prototype;g.h.FO=function(a,b,c,d){this.A.stop();if(!this.B){var e=g.Kh(a);this.u||(g.Ih(a,e.width),g.Ih(b,e.width));g.qh(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.qh(c,"right","1px");this.B=!0;g.Lh(a,!0);this.C=new g.J(function(){g.K(this.o,"iv-branding-active")},0,this);
this.C.start()}};
g.h.FF=function(a,b){g.Hn(this.o,"iv-branding-active");this.F=new g.J((0,g.x)(function(){g.Lh(a,!1);this.u||g.Ih(b,0)},this),250);
this.F.start();this.B=!1};
g.h.show=function(){if(!this.isActive){x3.prototype.show.call(this);if(!this.G){g.K(this.o,"iv-branding");var a=this.annotation.data;this.w=g.Rd("IMG",{"aria-label":"Channel watermark",src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Lh(this.w,!1);var b=g.Rd("DIV","branding-img-container",this.w);this.o.appendChild(b);(b=Qqa(this.annotation))&&this.Gj(this.w,b,this.annotation.id,a.session_data);if(a.channel_name){var c=g.Rd("DIV","iv-branding-context-name");
g.ae(c,a.channel_name);var d=g.Rd("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.u=new g.nQ(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.aa),this.u.ba(d);b=g.Rd("DIV","iv-branding-context-subscribe-caret");c=g.Rd("DIV","branding-context-container-inner",b,c,d);g.Lh(c,!1);d=g.Rd("DIV","branding-context-container-outer",c);g.qh(d,"right",
a.image_width+"px");this.o.appendChild(d);this.A=new g.J(g.Oa(this.FF,c,d),500,this);g.H(this,this.A);this.context.o.ia(this.o,"mouseover",(0,g.x)(this.FO,this,c,d,b,a.image_height));this.context.o.ia(this.o,"mouseout",(0,g.x)(this.A.start,this.A,void 0))}this.G=!0}g.Lh(this.o,!0);this.isActive=!0;if(this.w){a=this.w;var e=void 0===e?0:e;b=g.Dh(a);c=g.Kh(a);b=(new g.nh(b.x,b.y,c.width,c.height)).width;g.yh(a,b);e=new R2(a,[b,a.offsetTop],[b-b-e,a.offsetTop],200,pqa);g.H(this,e);this.context.w.ia(e,
"begin",g.Oa(g.Lh,a,!0));e.play()}}};
g.h.hide=function(){this.isActive&&(x3.prototype.hide.call(this),g.Lh(this.o,!1),this.isActive=!1)};
g.h.destroy=function(){this.u&&(this.u.dispose(),this.u=null);x3.prototype.destroy.call(this)};g.r(z3,x3);g.h=z3.prototype;g.h.show=function(){this.isActive||(x3.prototype.show.call(this),this.P||(ora(this),this.P=!0),g.Lh(this.o,!0),g.yf(function(){g.Hn(this.o,"iv-promo-inactive")},100,this),this.o.removeAttribute("aria-hidden"),this.isActive=!0,A3(this),qra(this),rra(this,this.G))};
g.h.hide=function(){this.isActive&&(g.K(this.o,"iv-promo-inactive"),this.isActive=!1,this.o.setAttribute("aria-hidden",!0))};
g.h.On=function(a,b,c,d,e,f){return this.C?!1:x3.prototype.On.call(this,a,b,c,d,e,f)};
g.h.fr=function(a,b){b.stopPropagation();qra(this);rra(this,a);this.u.focus()};
g.h.jF=function(a){this.J=!0;this.fr(500,a)};
g.h.iF=function(){this.J=!1;pra(this)};
g.h.aF=function(a){a.stopPropagation();this.hide()};
g.h.bF=function(a){a.stopPropagation();A3(this);this.C=!0;g.K(this.o,"iv-promo-collapsed-no-delay");this.F.start()};
g.h.destroy=function(){this.F.dispose();x3.prototype.destroy.call(this)};g.r(B3,g.HP);g.h=B3.prototype;g.h.Mc=function(a,b){if(!ura(this.player.N().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.T1(b);c&&C3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(hra(this.o,b),J2(this.player)),!0}return null};
g.h.getOptions=function(){return ura(this.player.N().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.Io=function(){if(this.A){var a=g.lL(this.player).getVideoContentRect(!0);g.Jh(this.A.element,a.width,a.height);g.yh(this.A.element,a.left,a.top)}if(this.o){var b=g.xL(this.player);a=this.o;b=b.width;g.L(a.F,"iv-drawer-small",426>=b);g.L(a.F,"iv-drawer-big",1280<=b)}};
g.h.eM=function(a){this.oc(a.state);g.W(a.state,2)&&(this.bl()&&this.Dy()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Yr(!1))};
g.h.load=function(){g.HP.prototype.load.call(this);this.oc(g.oL(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.SK,this,b,this.H),d=(0,g.x)(function(){this.C=null},this);
g.Hp()&&(c=yra(this,c));c={format:"XML",wd:c,onError:d,Wd:{}};a.isPharma&&(c.Wd.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.N().F.get(b))&&zra(c,b);b=b&&(b.Om||b.Nm);if(!a.Bm||b)a.Xd?vra(this,a.Xd,c):(this.w=(0,g.x)(this.xG,this,c),this.player.addEventListener("videodatachange",this.w));g.GL(this.player,this.A.element,4);this.Io();(b=g.JB(a))&&Era(this,b);(b=g.KB(a))&&b.featuredChannel&&Fra(this,b.featuredChannel,b.annotationId||"branding",a.videoId||null,a.eventId||null)};
g.h.oc=function(a){a=!a.isCued()&&!g.W(a,1024);g.BC(this.u,a);g.BC(this.A,a)};
g.h.xG=function(a){var b=this.player.getVideoData();b.Xd&&(this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null),vra(this,b.Xd,a))};
g.h.unload=function(){g.YQ(this.player.app,"annotations_module",void 0);g.Lb(this.F,function(a){a.destroy()});
this.G=null;this.o&&(this.o.destroy(),this.o=null,J2(this.player));this.J=!1;this.C&&(this.C.abort(),this.C=null);this.F={};this.u.hide();g.HP.prototype.unload.call(this);g.yC(this.A);this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null)};
g.h.SK=function(a,b,c){this.C=null;!xra(this,b,a)&&(a=g.mp(c)&&c.responseXML?c.responseXML:null)&&(C3(this,a),g.K(g.mL(this.player),"iv-module-loaded"))};
g.h.LA=function(a){a==this.player.getVideoData().videoId&&(this.loaded?Ara(this):this.load())};
g.h.bl=function(){return!!this.o&&this.o.isAvailable()};
g.h.Dy=function(){this.bl();return!!this.o&&this.o.C};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.bl();this.o&&(a?c?p3(this.o,c,b):p3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):q3(this.o))};
g.h.Yr=function(a,b){this.player.R(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.Y=function(){this.player.N().F.unsubscribe("vast_info_card_add",this.LA,this);g.Hn(g.mL(this.player),"ytp-iv-drawer-open");for(var a=this.P,b=0,c=a.length;b<c;b++)g.Ip(a[b]);this.P.length=0;g.HP.prototype.Y.call(this)};g.WP.annotations_module=B3;g.WP.creatorendscreen=V2;})(_yt_player);
